
language: ruby

rvm:
  - 2.3.4

env:
  - TRAVIS_NODE_VERSION="8.0.0"

notifications:
  email: false

addons:
  postgresql: 9.4
  apt:
    packages:
      - postgresql-9.4-postgis-2.3

before_script:

  # Enable PostGIS.
  - psql -U postgres -c "CREATE EXTENSION POSTGIS"

  # Create database, apply Travis config.
  - psql -c "CREATE DATABASE graves_test;" -U postgres
  - psql -c "CREATE DATABASE graves_legacy;" -U postgres
  - cp config/database.yml.travis config/database.yml

  # Load the schema.
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare

  # Build static payloads.
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - node --version
  - npm install -g npm@5.0.1
  - npm --version
  - npm install -g grunt-cli
  - npm install

script:

  - bundle exec rake
  - grunt compile:min
  - grunt jasmine
